version: "3"
name: solr-kural
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    env_file: .env
    working_dir: ${CORE_DIR}
    volumes:
      - data:/var/solr
      - ./solrconfig.xml:/opt/solr/server/solr/configsets/_default/conf/solrconfig.xml
      - ./managed-schema.xml:/opt/solr/server/solr/configsets/_default/conf/managed-schema.xml
      - ./kural-fields.json:${CORE_FIELDS}
      # - ./kurals.json:${CORE_SAMPLE_DATA}
      - ./strapi-kural.json:${CORE_SAMPLE_DATA}
      - ./solr-extended-core.sh:${CORE_DIR}/solr-extended-core.sh
    #command:
    #  - solr-precreate
    #  - gettingstarted
    entrypoint: bash -c "echo starting solr-extended-core; ./solr-extended-core.sh"
volumes:
  data:
